/*
 * ClientsAPI-Production
 * The Client Management APIs provide a comprehensive set of endpoints for managing clients within the system. These APIs facilitate operations such as creating, retrieving, updating, and deleting client information.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.57
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ClientsApiProduction);
  }
}(this, function(expect, ClientsApiProduction) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ClientsApiProduction.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('getPingStatus', function() {
        it('should call getPingStatus successfully', function(done) {
          // TODO: uncomment, update parameter values for getPingStatus call
          /*
          var opts = {};

          instance.getPingStatus(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1PingOptions', function() {
        it('should call v1PingOptions successfully', function(done) {
          // TODO: uncomment, update parameter values for v1PingOptions call
          /*
          var opts = {};

          instance.v1PingOptions(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
